### PR TITLE
Re-sized date columns to prevent them from splitting the dates

### PR DESCRIPTION
**Pull request by mattdebont**
Just a simple addition, prevents the datatables plugin from splitting the date columns as it just looks terrible in my opinion

### CODE REVIEW

**Comment by chrisjohnson1988** [comment]
Hey Matt,

Can you give me an example of when this issue occurs? Just want to test in different setups

Chris

**Comment by mattdebont** [comment]
Ok, that is very odd, I had it always happening and now it isn’t at all, so I guess we can just scrub this pull. Basically it was just splitting the dates across lines as the new taxon name column just pushed things to the side, looks fine now so I have no idea what I did to get it appear.

Matt

**Comment by chrisjohnson1988** [comment]
Hmm.... I think Jon managed to get it to occur then. Just wondering if this fix fill fully address that issue then

**Comment by mattdebont** [comment]
Looking at it this way, probably not, we would have to give them a fixed width, it’s just a case of fiddling with sizes more than anything there

**Comment by joncooper65** [comment]
Someone asked if the date format could be changed at a meeting yesterday - I think your change would make it a bit tidier.  Image below just clarifies what you are talking about.

**Pull request merged**
